# Generated by Django 4.2.30 on 2026-05-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("company", models.CharField(blank=True, max_length=150)),
                ("phone", models.CharField(max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("route", models.CharField(blank=True, max_length=150)),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_processed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(unique=True)),
                ("title_hy", models.CharField(max_length=255)),
                ("title_ru", models.CharField(max_length=255)),
                ("title_en", models.CharField(max_length=255)),
                ("subtitle_hy", models.TextField(blank=True)),
                ("subtitle_ru", models.TextField(blank=True)),
                ("subtitle_en", models.TextField(blank=True)),
                ("body_hy", models.TextField(blank=True)),
                ("body_ru", models.TextField(blank=True)),
                ("body_en", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(default="ti-building", max_length=100)),
                ("color", models.CharField(default="#f59e0b", max_length=20)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="RoutePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_hy", models.CharField(max_length=100)),
                ("name_ru", models.CharField(max_length=100)),
                ("name_en", models.CharField(max_length=100)),
                ("x", models.FloatField(default=500)),
                ("y", models.FloatField(default=250)),
                ("size", models.PositiveIntegerField(default=7)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.CharField(default="ti-truck-delivery", max_length=100)),
                ("name_hy", models.CharField(max_length=255)),
                ("name_ru", models.CharField(max_length=255)),
                ("name_en", models.CharField(max_length=255)),
                ("desc_hy", models.TextField()),
                ("desc_ru", models.TextField()),
                ("desc_en", models.TextField()),
                (
                    "tags_hy",
                    models.CharField(
                        blank=True, help_text="Comma separated", max_length=255
                    ),
                ),
                (
                    "tags_ru",
                    models.CharField(
                        blank=True, help_text="Comma separated", max_length=255
                    ),
                ),
                (
                    "tags_en",
                    models.CharField(
                        blank=True, help_text="Comma separated", max_length=255
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo_text", models.CharField(default="Trust Way", max_length=100)),
                (
                    "phone_main",
                    models.CharField(default="+374 33 787790", max_length=50),
                ),
                (
                    "phone_second",
                    models.CharField(
                        blank=True, default="+374 043 00 33 59", max_length=50
                    ),
                ),
                (
                    "phone_third",
                    models.CharField(
                        blank=True, default="+374 95 608020", max_length=50
                    ),
                ),
                (
                    "email",
                    models.EmailField(default="logistics@trustway.am", max_length=254),
                ),
                (
                    "address_hy",
                    models.CharField(default="Երևան, Հայաստան", max_length=255),
                ),
                (
                    "address_ru",
                    models.CharField(default="Ереван, Армения", max_length=255),
                ),
                (
                    "address_en",
                    models.CharField(default="Yerevan, Armenia", max_length=255),
                ),
                (
                    "whatsapp_number",
                    models.CharField(default="37433787790", max_length=50),
                ),
                ("telegram_link", models.URLField(default="https://t.me/+37433787790")),
                (
                    "footer_text_hy",
                    models.TextField(default="Միջազգային լոգիստիկ լուծումներ։"),
                ),
                (
                    "footer_text_ru",
                    models.TextField(default="Международные логистические решения."),
                ),
                (
                    "footer_text_en",
                    models.TextField(default="International logistics solutions."),
                ),
            ],
            options={
                "verbose_name": "Site settings",
                "verbose_name_plural": "Site settings",
            },
        ),
        migrations.CreateModel(
            name="Stat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=30)),
                ("label_hy", models.CharField(max_length=100)),
                ("label_ru", models.CharField(max_length=100)),
                ("label_en", models.CharField(max_length=100)),
                ("icon", models.CharField(default="ti-chart-bar", max_length=100)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ValueItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.CharField(default="ti-shield-check", max_length=100)),
                ("title_hy", models.CharField(max_length=255)),
                ("title_ru", models.CharField(max_length=255)),
                ("title_en", models.CharField(max_length=255)),
                ("desc_hy", models.TextField()),
                ("desc_ru", models.TextField()),
                ("desc_en", models.TextField()),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="WorkStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num", models.CharField(default="01", max_length=10)),
                ("name_hy", models.CharField(max_length=255)),
                ("name_ru", models.CharField(max_length=255)),
                ("name_en", models.CharField(max_length=255)),
                ("desc_hy", models.TextField()),
                ("desc_ru", models.TextField()),
                ("desc_en", models.TextField()),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
