# Generated by Django 6.0.5 on 2026-05-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_hy", models.CharField(max_length=255)),
                ("title_ru", models.CharField(max_length=255)),
                ("title_en", models.CharField(max_length=255)),
                ("url", models.CharField(default="#", max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Footer link",
                "verbose_name_plural": "Footer links",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
