# Generated by Django 6.0.5 on 2026-05-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_footerlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="logo_image",
            field=models.ImageField(blank=True, null=True, upload_to="site/"),
        ),
    ]
