# Generated by Django 6.0.5 on 2026-05-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_sitesettings_logo_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="logo_image",
            field=models.FileField(blank=True, null=True, upload_to="site/"),
        ),
    ]
