# Generated by Django 6.0.5 on 2026-05-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_sitesettings_logo_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="favicon",
            field=models.ImageField(blank=True, null=True, upload_to="site/"),
        ),
    ]
