# Generated by Django 6.0.5 on 2026-05-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_sitesettings_favicon"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagecontent",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="pages/"),
        ),
    ]
