# Generated by Django 6.0.5 on 2026-05-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_pagecontent_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagecontent",
            name="image",
        ),
        migrations.AddField(
            model_name="pagecontent",
            name="content_image",
            field=models.ImageField(blank=True, null=True, upload_to="pages/content/"),
        ),
        migrations.AddField(
            model_name="pagecontent",
            name="hero_image",
            field=models.ImageField(blank=True, null=True, upload_to="pages/hero/"),
        ),
    ]
