# Generated by Django 6.0.5 on 2026-05-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_pagecontent_image_pagecontent_content_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="routepoint",
            name="lat",
            field=models.FloatField(default=40.1772),
        ),
        migrations.AddField(
            model_name="routepoint",
            name="lng",
            field=models.FloatField(default=44.5035),
        ),
    ]
