# Generated by Django 6.0.5 on 2026-05-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_routepoint_lat_routepoint_lng"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partner",
            options={
                "ordering": ["sort_order", "id"],
                "verbose_name": "partner",
                "verbose_name_plural": "partners",
            },
        ),
        migrations.RemoveField(
            model_name="partner",
            name="color",
        ),
        migrations.RemoveField(
            model_name="partner",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="partner",
            name="name",
        ),
        migrations.AddField(
            model_name="partner",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="partners/",
                verbose_name="Partner logo",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="name_en",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="partner",
            name="name_hy",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="partner",
            name="name_ru",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
