# Generated by Django 6.0.5 on 2026-05-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_partner_options_remove_partner_color_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partner",
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.RemoveField(
            model_name="partner",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="partner",
            name="name_hy",
        ),
        migrations.RemoveField(
            model_name="partner",
            name="name_ru",
        ),
        migrations.AddField(
            model_name="partner",
            name="color",
            field=models.CharField(default="#f59e0b", max_length=20),
        ),
        migrations.AddField(
            model_name="partner",
            name="icon",
            field=models.CharField(default="ti-building", max_length=100),
        ),
        migrations.AddField(
            model_name="partner",
            name="name",
            field=models.CharField(default="Partner", max_length=100),
        ),
        migrations.AlterField(
            model_name="partner",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="partners/"),
        ),
    ]
