# Generated by Django 6.0.5 on 2026-05-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_partner_options_remove_partner_name_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="jctrans_logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="site/", verbose_name="JCTRANS logo"
            ),
        ),
    ]
